---
title: "run targets"
format:
  html:
    toc: true
---

```{r}
library(targets)
library(tarchetypes)
```

```{r}
tar_manifest()
```

```{r}
tar_make()
```


```{r}
tar_visnetwork()
```

```{r}
tar_load(seurat_obj_raw_joined)
seurat_obj_raw_joined
```



```{r}
tar_option_set(
  packages = c(
    "here",
    "Seurat",
    "BPCells"
  ),
  format = "qs",
)

tar_load_globals()
tar_meta(fields = error, complete_only = TRUE)

library(qs2)
tar_load(bpcells_cellranger_cmo)
```


```{r}
expand.grid(var1 = c("a", "b"), var2 = c("c", "d"), rep = c(1, 2, 3))

```

```{r}
library(tibble)
tibble(
  method_function = rlang::syms(c("method1", "method2")),
  data_source = c("NIH", "NIAID")
)
```

## Debugging
```{r}
library(targets)
library(tarchetypes)

# Loads globals like tar_option_set() packages, simulate_data(), and analyze_data():

tar_make()
targets::tar_meta(fields = error, complete_only = TRUE)|>View()
```


# tar_load(seurat_obj_raw_joined)
# seurat_obj_raw_joined

# tar_load(dataset)
# tar_load(bpcells_cellbender)
# tar_load(bpcells_cellranger)
# tar_load(bpcells_cellranger_cmo)
# tar_load(convert_vector)

# create_joined_seurat_obj()




```{r}
tar_visnetwork(allow=contains("hub_01"))
```